spring:
  profiles:
    active: dev  # 기본 활성화 프로파일 (개발 환경)

# 공통 설정
server:
  servlet:
    context-path: /api

---
# 개발 환경 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/stt
    username: user
    password: qlalfqjsgh
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8081

vito:
  client_id: xdvYmyTbW9uUK9MBAouu
  client_secret: ObuvZHdGB89w-g4IzMK9x23364CtfSdAttLPvnsR

file:
  path: C:\GitHub\okr\audio

---

# 배포 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://52.79.215.156:3306/okr_stt
    username: root
    password: qlalfqjsgh
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8081

vito:
  client_id: xdvYmyTbW9uUK9MBAouu
  client_secret: ObuvZHdGB89w-g4IzMK9x23364CtfSdAttLPvnsR

file:
  path: /home/ec2-user/okr_stt/record