spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/stt
    username: user
    password: qlalfqjsgh
    driver-class-name: org.mariadb.jdbc.Driver

server:
  servlet:
    context-path: /api

vito:
  client_id: xdvYmyTbW9uUK9MBAouu
  client_secret: ObuvZHdGB89w-g4IzMK9x23364CtfSdAttLPvnsR